@TaskManager_TaskApiAddress = https://localhost:7096/api/tasks

GET {{TaskManager_TaskApiAddress}}?page=0&count=5
Accept: application/json

###
POST {{TaskManager_TaskApiAddress}}
Content-Type: application/json
{
    "title": "new task",
    "description": "some description",
    "dueDate": "2025-07-09T19:25:43.511Z"
}
###

###
POST {{TaskManager_TaskApiAddress}}
Content-Type: application/json
{
    "title": "new task 2",
    "description": "some description",
    "dueDate": "2025-07-09T19:25:43.511Z"
}
###

###
PATCH {{TaskManager_TaskApiAddress}}
Content-Type: application/json
{
    "id": 11,
    "status": 1
}

###
GET {{TaskManager_TaskApiAddress}}/11


###
GET {{TaskManager_TaskApiAddress}}/error
